name: Delete Deployments

on:
  workflow_dispatch:
    inputs:
      environment-name: 
        description: 'Name of Environment to generate'
        required: true
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.inputs.environment-name }}